services:
  db:
    image: postgres
    container_name: mistral_db
    hostname: mistral_db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
