services:
  app:
    # image: ghcr.io/lordluceus/chat-lounge:master
    build: .
    ports:
      - 3000:3000
      # Socket.io server for import progress
      - 4001:4001
    env_file:
      - .env
    container_name: chat-lounge
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      valkey:
        condition: service_started

  valkey:
    image: valkey/valkey:latest # Use the official Valkey image
    container_name: valkey-server
    restart: unless-stopped
    command: [ "valkey-server", "/usr/local/etc/redis.conf" ]
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf

  db:
    image: mariadb:11.4
    container_name: chat-lounge-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db-data:
