services:
  app:
    image: ghcr.io/lordluceus/chat-lounge:master
    ports:
      - 3000:3000
    env_file:
      - .env
    container_name: chat-lounge
    restart: unless-stopped
    depends_on:
      - valkey
    volumes:
      - db-data:/app/data

  valkey:
    image: valkey/valkey:latest # Use the official Valkey image
    container_name: valkey-server
    restart: unless-stopped
    command: [ "valkey-server", "/usr/local/etc/redis.conf" ]
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf

volumes:
  db-data:
