// Generated by https://quicktype.io

export interface ElevenLabsError {
  detail: Detail;
}

export interface Detail {
  status: string;
  message: string;
  character_used?: number;
  character_limit?: number;
}
